### ISSUE TITLE
Profanity Filter

### ISSUE THREAD

**Issue by dkgrizzly** [TitanEmbeds/Titan#102]
I patched my local copy for using https://github.com/areebbeigh/profanityfilter

[TitanProfanityFilterPatch.txt](https://github.com/TitanEmbeds/Titan/files/1897404/TitanProfanityFilterPatch.txt)

This could have an option created (dbguild.chat_profanity ?) that would enable/disable the filter, or possibly be enhanced to add a middle option of censoring.

**Comment by EndenDragon** [comment]
Profanity filter is now implemented! https://github.com/TitanEmbeds/Titan/commit/ccf9aed9ec718221db21a4f311e5c3b9b12f8d80
