### ISSUE TITLE
markdown in bot embeds doesn't work

### ISSUE THREAD

**Issue by cmdwm** [TitanEmbeds/Titan#117]
boat broake
![screenshot_20180726-012119](https://user-images.githubusercontent.com/35583237/43243052-6f345e16-9072-11e8-964d-9294864615b0.png)

**Comment by EndenDragon** [comment]
Reminds me of the android Discord that used to not support markdown in Rich Embeds. Thanks for filing a bug!

**Comment by EndenDragon** [comment]
Implemented in https://github.com/TitanEmbeds/Titan/commit/6578526ef668819ff58a002c5b93cd916e6c17c7
