### ISSUE TITLE
CORS policy violation

### ISSUE THREAD

**Issue by thedustyrover** [TitanEmbeds/Titan#131]
Trying to integrate for the first time but getting the following:

`Access to XMLHttpRequest at 'https://discordapp.com/api/guilds/..../widget.json' from origin 'https://titanembeds.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

This is between discordapp.com and titanembeds right? There's no special header I can set to allow this?

**Comment by circl-lastname** [comment]
Does this break the embed?

**Comment by circl-lastname** [comment]
Does this break the embed?

**Comment by EndenDragon** [comment]
Correct, this is an issue with Discord API and there are no means of resolving this issue. Only time will tell when they fixes it.

On a side note, the widget.json is fetched by Titan to populate the instant invite button. That would be about it, so you can probably ignore this issue.
