### ISSUE TITLE
Add Variable CSS Color System

### ISSUE THREAD

**Issue by julianschiavo** [TitanEmbeds/Titan#14]
- [x] Add a way for users to enter hex colors into an editor OR choose to use advanced CSS as before
- [x] Use those in the web app as CSS variables
- [ ] Load base color CSS together with variables

If implemented correctly this should allow for non technical users to change colors and CSS without requiring the technical knowledge to make full themes. It should also allow for much *quicker* customisation by technical users as well.

**Comment by EndenDragon** [comment]
Created a branch ([EndenDragon/cssvars](/EndenDragon/Titan/tree/cssvars)) to implement CSS Variables feature
