### ISSUE TITLE
Website alternatives

### ISSUE THREAD

**Issue by Harp3rDev** [TitanEmbeds/Titan#142]
I'm not sure you can do this, but maybe make alternative websites of titanembeds to embed instead
because it is blocked at my school. I used this because it works at home on Chromebooks, but it doesn't work at school. You don't have to do this, it is just an idea.

**Comment by EndenDragon** [comment]
Thanks for the comment. However it's not our goal to build a Discord adapter to bypass network filters. Committing to that project idea would create more financial burden with little to no in return.
