### ISSUE TITLE
New to this.  Can you view webcams in the embedded version?

### ISSUE THREAD

**Issue by gaveitatry02** [TitanEmbeds/Titan#147]
Hi.  I haven't installed Titan or tested it out yet.  I'm wondering about webcams.  If someone is using the pc version of Discord to stream their webcam, can another person view that webcam in the embedded version?  Please let me know.  Thank you.

**Comment by jelle619** [comment]
Titan Embeds is for Discord text channels only. You cannot use it for voice channels and, by extension, watch video and webcam streams.
