### ISSUE TITLE
Is there a way to embed notification of new direct messages?

### ISSUE THREAD

**Issue by gaveitatry02** [TitanEmbeds/Titan#148]
I don't like having Discord running because I don't really use it.  I don't like having it pinned to the Taskbar.  And I don't like going to the Start Menu and looking for the program shortcut and starting up Discord now and then to see if I have any new messages.  So I'm thinking I want a way to embed a notification button or something that shows a different display or alert whenever I have new, unread DMs.  Is something like that possible with TItan?

**Comment by omnicons** [comment]
It is not, as the bot is meant to have handle serving up one guild at a time, not a person's user account.
