### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by jorivanee** [TitanEmbeds/Titan#15]
Currently the embed gives you access to see every channel and their contents, we should make it so for guest users you can only view the channels the @everyone role can view, and for logged in users we follow their permissions.

**Comment by julianschiavo** [comment]
Agreed 👍

**Comment by EndenDragon** [comment]
Strange, it should work as intended, hiding the channels that the users cannot see, and also muting the channels if they cannot post. It is handled in this function https://github.com/EndenDragon/Titan/blob/master/webapp/titanembeds/blueprints/api/api.py#L152

You guys can try StreamersConnected discord server as an example. They got the introduction channel (which you should see the chat as locked) and also you guys shouldn't be able to see # contributor-chat channel (but it exists, as i am in it). https://titanembeds.tk/embed/252999442465030144

But if you guys really want to try stuff yourself, set up a test server and play with the overwrites and stuff.

If you see any further permissions problems, please reopen this issue with evidence and I'll look deeper into this cause.
