### ISSUE TITLE
Can you add a login to the page without discord? I want to configure it from school, but discord is blocked.

### ISSUE THREAD

**Issue by Adithr123** [TitanEmbeds/Titan#154]
Thanks!

**Comment by EndenDragon** [comment]
Hello and thanks for filling an suggestion. However, circumventing school blocks is beyond our scope of this project and we are not looking into addressing this issue. However, we do support guest logins if that is what you're looking for. When enabled under the Titan dashboard, you can pick any username without leaving Titan and proceed into the server.

**Comment by Adithr123** [comment]
On the main website, I want to be able to access the main dashboard to edit the widget and bot. I am proposing a login system with a username and password.
