### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by jorivanee** [TitanEmbeds/Titan#23]
Admin Panel TODO:

- [x] Create base
- [x] Add cosmetic management system
- [x] Copy the normal dashboard but instead of only adding the servers you can manage, bot admins can manage every server, maybe also a search for server by ID/Name/Owner/Owner ID

**Comment by julianschiavo** [comment]
Who will be allowed to access the admin panel?

Edit: SHIT accidentally pressed close. SORRY!

**Comment by EndenDragon** [comment]
@dottJS For now, maffie has hard coded just me and him to access the panel. However I probably am going to switch the system so that the names in the database or the config can be changed to enable admin access for the users.

**Comment by julianschiavo** [comment]
You better put me in :eyes:

**Comment by jorivanee** [comment]
@EndenDragon I have hardcoded me, .js and u in already, I want to keep it hardcoded for security purposes

**Comment by EndenDragon** [comment]
@JustMaffie I understand, but no one has access to the MySQL server unless I give them my login to both the webhost and the mysql itself. If that isn't secure, then a _hacker_ would have better things to do (such as changing the guild's name) than to add himself to the administrator's table and toggle css for people.

**Comment by jorivanee** [comment]
Alright, I've finished this, more features will probably be added in the future
