### ISSUE TITLE
Use webhooks for sending messages

### ISSUE THREAD

**Issue by RaidAndFade** [TitanEmbeds/Titan#42]
Webhooks allow you to have a custom avatar and username for each message, they can make this much cleaner.

**Comment by EndenDragon** [comment]
Webhooks is implemented in the sense that the server owner have to create a webhook of their own, starting with the name of [Titan] or Titan. (See the webhook panel in the about page - https://titanembeds.tk/about). 
However, I'm going to keep this open and implement a better resolution after the websockets update. The resolution will include a toggle in the server settings dashboard and will work in all channels (with each users having their own webhook - so libs like discord.js won't cache the username and works better on the mobile discord platforms). Stay tuned for this!
