### ISSUE TITLE
Animated Avatars

### ISSUE THREAD

**Issue by EndenDragon** [TitanEmbeds/Titan#61]
Because this should be a thing

**Comment by jelle619** [comment]
Great! But first take some rest, please, you deserve it.

**Comment by acobeppp** [comment]
yes

**Comment by acobeppp** [comment]
yes 2

**Comment by jelle619** [comment]
Glad you agree on that second one. :'-)

**Comment by EndenDragon** [comment]
Currently animated avatars has been implemented. Not by hover, but by the member sidebar and the user cards.
