### ISSUE TITLE
Migrate to rewrite version of discord.py (bot)

### ISSUE THREAD

**Issue by kotx** [TitanEmbeds/Titan#71]
It's just better 😄 . To prevent buggy code from manual editing, you should use async2rewrite along with manual editing. Just because it's the "rewrite version" doesn't mean it's unstable 😉 
Anyway, thanks.

**Comment by EndenDragon** [comment]
Ooh, I didn't know async2rewrite is a thing before. That can certainly come in handly. For now, I am going to wait until discord.py rewrite is released in PyPI or when I rewrite the whole Titan Embeds (whichever happens to be first). Currently, the async branch of discord.py works very well for us (despite the fact that I have forked the lib and edited some of the features myself). It doesn't need immediate attention to switch. However, I am keeping this issue open to remind me possibly over the summer (when I rewrite the project) to update my discord.py. Thanks for noticing! :)

**Comment by jorivanee** [comment]
@EndenDragon you can assign this to me, I can move Titan to Rewrite

**Comment by EndenDragon** [comment]
Our server count is growing faster than ever. ...faster than what I had initially thought. I am going to switch Titan over to the dpy rewrite branch now.
