### ISSUE TITLE
Emoticons don't work :(

### ISSUE THREAD

**Issue by Jake0303** [TitanEmbeds/Titan#96]
Just noticed that emoticons don't work, try typing and entering :D or :P in a embed page. 
![untitled](https://user-images.githubusercontent.com/5394743/37596029-32533aa2-2b51-11e8-9796-aff98f5e3490.png)

**Comment by EndenDragon** [comment]
An implementation is coming soon:tm:!

**Comment by ghost** [comment]
t r a d e m a r k
